server:
  port: ${SERVER_PORT:8083}
  reactive:
    session:
      timeout:
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}

spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/vogorode}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: vogorode
      host: localhost
      port: 27017

rest:
  landscape:
    url: ${LANDSCAPE_URL:http://localhost:8082}
