{
 "title": "Handyman Service",
 "tags": [
  "cpu",
  "memory",
  "jvm",
  "business-request-duration",
  "handyman-service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Handyman CPU usage in percents",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"vogorode-handyman-spring\"}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "description": "Handyman memory usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"vogorode-handyman-spring\"}"
    }
   ]
  },
  {
   "title": "Workers requests",
   "type": "timeseries",
   "description": "Handyman workers request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"handyman-service\", process=\"worker\"}[2m])))"
    }
   ]
  },
  {
   "title": "Accounts requests",
   "type": "timeseries",
   "description": "Handyman accounts request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"handyman-service\", process=\"account\"}[2m])))"
    }
   ]
  },
  {
   "title": "Users requests",
   "type": "timeseries",
   "description": "Handyman user request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"handyman-service\", process=\"user\"}[2m])))"
    }
   ]
  }
 ]
}