{
 "title": "Landscape Service",
 "tags": [
  "cpu",
  "memory",
  "jvm",
  "business-request-duration",
  "landscape-service",
  "stat-request-duration"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Landscape CPU usage in percents",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"vogorode-landscape-spring\"}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "description": "Landscape memory usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"vogorode-landscape-spring\"}"
    }
   ]
  },
  {
   "title": "Sites requests",
   "type": "timeseries",
   "description": "Landscape sites request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"landscape-service\", process=\"site\"}[2m])))"
    }
   ]
  },
  {
   "title": "Users requests",
   "type": "timeseries",
   "description": "Landscape business request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"landscape-service\", process=\"user\"}[2m])))"
    }
   ]
  },
  {
   "title": "Orders requests",
   "type": "timeseries",
   "description": "Landscape orders request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"landscape-service\", process=\"order\"}[2m])))"
    }
   ]
  },
  {
   "title": "Accounts Stat duration",
   "type": "timeseries",
   "description": "Accounts stat handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(stat_request_duration_seconds_bucket{job=\"vogorode-landscape-spring\", stat=\"account\"}[2m])))"
    }
   ]
  },
  {
   "title": "Banks Stat duration",
   "type": "timeseries",
   "description": "Banks Stat handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(stat_request_duration_seconds_bucket{job=\"vogorode-landscape-spring\", stat=\"bank\"}[2m])))"
    }
   ]
  },
  {
   "title": "Areas Stat duration",
   "type": "timeseries",
   "description": "Areas Stat handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(stat_request_duration_seconds_bucket{job=\"vogorode-landscape-spring\", stat=\"area\"}[2m])))"
    }
   ]
  }
 ]
}