{
 "title": "Rancher Service",
 "tags": [
  "cpu",
  "memory",
  "jvm",
  "business-request-duration",
  "rancher-service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Rancher CPU usage in percents",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"vogorode-rancher-spring\"}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "description": "Rancher memory usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"vogorode-rancher-spring\"}"
    }
   ]
  },
  {
   "title": "Gardens requests",
   "type": "timeseries",
   "description": "Rancher gardens request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"rancher-service\", process=\"garden\"}[2m])))"
    }
   ]
  },
  {
   "title": "Field requests",
   "type": "timeseries",
   "description": "Rancher fields request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"rancher-service\", process=\"field\"}[2m])))"
    }
   ]
  },
  {
   "title": "Fielders requests",
   "type": "timeseries",
   "description": "Rancher fielders request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"rancher-service\", process=\"fielder\"}[2m])))"
    }
   ]
  },
  {
   "title": "Order requests",
   "type": "timeseries",
   "description": "Rancher orders request handling duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(business_request_duration_seconds_bucket{service=\"rancher-service\", process=\"order\"}[2m])))"
    }
   ]
  }
 ]
}