apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  volumes:
    - name: pv-postgres
      hostPath: 
        path: postgres_data
  containers:
    - name: vogorode-postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: vogorode
        - name: POSTGRES_PASSWORD
          value: '123'
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: pv-postgres
          mountPath: /var/lib/postgresql/data
