version: '3.8'

networks:
  infrastructure-network:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: infrastructure-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vogorode
      POSTGRES_PASSWORD: 123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose: 
      - 5432
    ports:
      - 5433:5432
  mongo:
    image: mongo
    container_name: infrastructure-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vogorode
    volumes:
      - ./mongo_data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - infrastructure-network
  mongo-express:
    image: mongo-express
    container_name: infrastructure-mongo-express
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_URL: mongodb://root:example@mongo:27017
    expose:
      - 8081
    ports:
      - 5434:8081
    networks:
      - infrastructure-network
    depends_on:
      - mongo
  prometheus:
    image: prom/prometheus
    container_name: infrastructure-prometheus
    restart: always
    command:
      - --web.listen-address=:10000
      - --storage.tsdb.path=/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 10000
    ports:
      - 10000:10000
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    networks:
      - infrastructure-network
  grafana:
    image: grafana/grafana:8.2.6
    container_name: infrastructure-grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ../../monitoring:/etc/grafana/provisioning
    networks:
      - infrastructure-network
    depends_on:
      - prometheus
