version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vogorode-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vogorode
      POSTGRES_PASSWORD: 123
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    expose: 
      - 5432
    ports:
      - 5432:5432
  mongo:
    image: mongo
    container_name: vogorode-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vogorode
    expose:
      - 27017
    ports:
      - 27017:27017
