@startuml Context
!include <C4/C4_Container>

Person(owner, "Owner", "Владелец полей, может создавать заказы на работу.")
Person(worker, "Worker", "Ищет работу, управляет своим расписанием и навыками.")
Person(fielder, "Fielder", "Наблюдает за полями над которыми он работает.")

System(vogorode, "VOgorode", "Система предоставления сервиса по оказанию ландшафтных работ клиентам распределённым географически. Сервис подбирает исполнителей на основании географических координат исполнителя и локации заказчика, списка оказываемых исполнителем работ, а так же рейтинга исполнителя.")

Rel(owner, vogorode, "Регистрируется, смотрит информацию об аккаунте, смотрит статистику, создает заказы.", "http")
Rel(worker, vogorode, "Регистрируется, смотрит информацию об аккаунте, смотрит статистику, регистрируется как работник, изменяет банковские аккаунты, расписание, навыки.", "http")
Rel(fielder, vogorode, "Регистрируется, смотрит информацию об аккаунте, смотрит статистику, получает информацию о полях на которых работает.", "http")

SHOW_LEGEND()

@enduml
