@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class User {
  + getName(): String
  + setAccounts(List<BankAccount>): void
  + setPhoto(Byte[]): void
  + getId(): String
  + getSurname(): String
  + setName(String): void
  + getSkills(): WorkEnum[]
  + setEmail(String): void
  + getEmail(): String
  + getTelephone(): String
  + getAccounts(): List<BankAccount>
  + setId(String): void
  + builder(): UserBuilder
  + getPhoto(): Byte[]
  + setSurname(String): void
  + setSkills(WorkEnum[]): void
  + setTelephone(String): void
  + equals(Object): boolean
  + hashCode(): int
}
class UserController {
  + update(UserUpdateDto): User
  + getById(String): User
  + delete(String): void
  + save(UserCreateDto): User
  + findAll(boolean): List<User>
}
class UserCreateDto {
  + getName(): String
  + getSurname(): String
  + setEmail(String): void
  + getSkills(): WorkEnum[]
  + getEmail(): String
  + setTelephone(String): void
  + hashCode(): int
  + getTelephone(): String
  + setPhoto(Byte[]): void
  # canEqual(Object): boolean
  + equals(Object): boolean
  + getAccountsId(): List<String>
  + setAccountsId(List<String>): void
  + getPhoto(): Byte[]
  + setName(String): void
  + toString(): String
  + setSurname(String): void
  + setSkills(WorkEnum[]): void
}
class UserMapper {
  + updateUser(User, UserUpdateDto): User
  + dtoToUser(UserCreateDto): User
}
interface UserRepository << interface >>
class UserService {
  + findAllUnsorted(): List<User>
  + findAllSortedBySurname(): List<User>
  + findAll(boolean): List<User>
  + findById(String): Optional<User>
  + save(UserCreateDto): User
  + update(UserUpdateDto): User
  + getById(String): User
  + delete(String): void
}
class UserUpdateDto {
  + getName(): String
  + getId(): String
  + setAccountsId(List<String>): void
  + hashCode(): int
  + getSurname(): String
  + equals(Object): boolean
  + setEmail(String): void
  + setTelephone(String): void
  + getSkills(): WorkEnum[]
  + getEmail(): String
  # canEqual(Object): boolean
  + getTelephone(): String
  + getAccountsId(): List<String>
  + getPhoto(): Byte[]
  + setSurname(String): void
  + setId(String): void
  + setSkills(WorkEnum[]): void
  + setName(String): void
  + toString(): String
  + setPhoto(Byte[]): void
}

UserController "1" *-[#595959,plain]-> "userService\n1" UserService    
UserService    "1" *-[#595959,plain]-> "userMapper\n1" UserMapper     
UserService    "1" *-[#595959,plain]-> "userRepository\n1" UserRepository 
@enduml
