server:
  port: ${PORT:8082}
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  client:
    HandymanService:
      address: ${HANDYMAN_GRPC-SERVER_ADDRESS:localhost:9090}
      negotiation-type: PLAINTEXT
    RancherService:
      address: ${RANCHER_GRPC_SERVER_ADDRESS:localhost:9091}
      negotiation-type: PLAINTEXT
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://0.0.0.0:5432/vogorode}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
