# HandymanService pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handyman-service
spec:
  selector:
    matchLabels:
      app: handyman-service
  replicas: 2
  template:
    metadata:
      labels:
        app: handyman-service
    spec:
      containers:
        - image: handyman-service:latest
          name: handyman-service
          imagePullPolicy: Never
          env:
            - name: LANDSCAPE_URL
              value: http://landscape-service-service:8082
            - name: MONGO_DB_AUTH_DB
              value: admin
            - name: MONGO_DB_USERNAME
              value: root
            - name: MONGO_DB_PASSWORD
              value: example
            - name: MONGO_DB_DB
              value: vogorode
            - name: MONGO_DB_HOST
              value: mongo-service
            - name: MONGO_DB_PORT
              value: '27017'
          ports:
            - name: server
              containerPort: 8080
            - name: grpc-server
              containerPort: 9090
---
# HandymanService service
apiVersion: v1
kind: Service
metadata:
  name: handyman-service-service
spec:
  selector:
    app: handyman-service
  ports:
    - name: server
      port: 8080
      targetPort: server
    - name: grpc-server
      port: 9090
      targetPort: grpc-server
  type: LoadBalancer
