scrape_configs:
  - job_name: 'vogorode-handyman-spring'
    scrape_interval: 15s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'handyman-service:8080' ]

  - job_name: 'vogorode-rancher-spring'
    scrape_interval: 15s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'rancher-service:8081' ]

  - job_name: 'vogorode-landscape-spring'
    scrape_interval: 15s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'landscape-service:8082' ]

  - job_name: 'vogorode-postgresql'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
