server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    tags:
      service: rancher-service
  prometheus:
    metrics:
      export:
        enabled: true

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}

spring:
  data:
    mongodb:
      authentication-database: ${MONGO_DB_AUTH_DB:admin}
      username: ${MONGO_DB_USERNAME:root}
      password: ${MONGO_DB_PASSWORD:example}
      database: ${MONGO_DB_DB:vogorode}
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      auto-index-creation: true

mongock:
  enabled: true
  migration-scan-package:
    - ru.tinkoff.academy.migrations

rest:
  landscape:
    url: ${LANDSCAPE_URL:http://localhost:8082}

kafka:
  consumer:
    order-inform:
      kafka-brokers: ${KAFKA_BROKERS:localhost:10092}
      schema-registry: ${SCHEMA_REGISTRY:http://localhost:10001}
      topic: vogorode.order-inform.queue
